apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: bXktc2VjcmV0LXB3
kind: Secret
metadata:
  creationTimestamp: null
  name: passwd


# kubectl create secret generic passwd \
# --from-literal=MYSQL_ROOT_PASSWORD=my-secret-pw\
#  --from-literal=AUTH-PASSWORD=auth-password 
# --from-literal=secret-key=bXktc2VjcmV0LXB3