apiVersion: v1
data:
  apikey: MTdiZjRkZDY0OG1zaDYyYTY5MTAxY2I1ODYxYnAxYmMyMDJqc25kOWZiMmExZGI3YzE=
kind: Secret
metadata:
  creationTimestamp: null
  name: weather


# 17bf4dd648msh62a69101cb5861bp1bc202jsnd9fb2a1db7c1